// let myArray = [];
// myArray.push(2);
// myArray.push(8);
// myArray.push(true);
// myArray.push("2");
// console.log(myArray);
// myArray.unshift("s");
// console.log(myArray);
// myArray.pop();
// console.log(myArray);
// myArray.shift();
// console.log(myArray);
